import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Headerr/Header";
// import Footer from '@/components/Footer'
import { SidebarContext } from "@/context/Sidebar/SideBarContext";
import Providers from "@/app/provider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import dynamic from "next/dynamic";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Cafeteria",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <SidebarContext>
          <body className={inter.className}>
            <ToastContainer />
            {children}
          </body>
        </SidebarContext>
      </Providers>
    </html>
  );
}
