import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Headerr/Header'
// import Footer from '@/components/Footer'
import Footer from '@/components/Footer'
import { SidebarContext } from '@/context/Sidebar/SideBarContext'
import Providers from '@/redux/Providers'
// import { store } from '@/redux/store'
// import { Provider } from 'react-redux'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import dynamic from 'next/dynamic'
const inter = Inter({ subsets: ['latin'] })
const PersistedReduxProvider = dynamic(() => import('@/redux/Providers'), {
  ssr: false,
})
export const metadata = {
  title: 'Cafeteria',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <Providers>
        <SidebarContext>
          <body className={inter.className}>
            <ToastContainer />
            {children}
          </body>
        </SidebarContext>
      </Providers>
    </html>
  )
}
