import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Headerr/Header'
// import Footer from '@/components/Footer'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Cafeteria',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
